#Konfiguracja symulacji: AtakPasozytow
#Wed Jan 21 16:25:03 CET 2026
energyLossForParasiteWithoutHost=2
energyLossPerDay=1
energyPerGrass=10
genomeLength=8
hostEnergyLossPerParasite=5
mapHeight=15
mapWidth=15
maximumMutations=2
minimumMutations=0
newGrassPerDay=5
saturationEnergy=15
startAnimalEnergy=30
startAnimalNumber=30
startGrassNumber=30
startParasiteEnergy=20
startParasiteNumber=30
