#Konfiguracja symulacji: du\u017Ca_mapa
#Fri Jan 23 09:40:06 CET 2026
energyLossForParasiteWithoutHost=2
energyLossPerDay=1
energyPerGrass=5
genomeLength=5
hostEnergyLossPerParasite=3
mapHeight=40
mapWidth=40
maximumMutations=2
minimumMutations=0
newGrassPerDay=20
saturationEnergy=200
startAnimalEnergy=150
startAnimalNumber=40
startGrassNumber=7
startParasiteEnergy=150
startParasiteNumber=40
