#Konfiguracja symulacji: unstable
#Fri Jan 23 10:28:21 CET 2026
energyLossForParasiteWithoutHost=2
energyLossPerDay=1
energyPerGrass=10
genomeLength=8
hostEnergyLossPerParasite=3
mapHeight=20
mapWidth=20
maximumMutations=2
minimumMutations=0
newGrassPerDay=6
saturationEnergy=70
startAnimalEnergy=100
startAnimalNumber=100
startGrassNumber=7
startParasiteEnergy=100
startParasiteNumber=40
