#Konfiguracja symulacji: Niestabilna
#Wed Jan 21 16:19:31 CET 2026
energyLossForParasiteWithoutHost=0
energyLossPerDay=2
energyPerGrass=10
genomeLength=8
hostEnergyLossPerParasite=0
mapHeight=15
mapWidth=15
maximumMutations=2
minimumMutations=0
newGrassPerDay=5
saturationEnergy=7
startAnimalEnergy=20
startAnimalNumber=15
startGrassNumber=50
startParasiteEnergy=0
startParasiteNumber=0
