#Konfiguracja symulacji: test3
#Thu Jan 22 21:53:56 CET 2026
energyLossForParasiteWithoutHost=0
energyLossPerDay=1
energyPerGrass=5
genomeLength=8
hostEnergyLossPerParasite=0
mapHeight=15
mapWidth=15
maximumMutations=2
minimumMutations=0
newGrassPerDay=4
saturationEnergy=10
startAnimalEnergy=20
startAnimalNumber=20
startGrassNumber=10
startParasiteEnergy=0
startParasiteNumber=0
