#Konfiguracja symulacji: test2
#Wed Jan 21 15:15:05 CET 2026
energyLossForParasiteWithoutHost=1
energyLossPerDay=1
energyPerGrass=5
genomeLength=8
hostEnergyLossPerParasite=1
mapHeight=20
mapWidth=20
maximumMutations=2
minimumMutations=0
newGrassPerDay=2
saturationEnergy=5
startAnimalEnergy=100
startAnimalNumber=4
startGrassNumber=7
startParasiteEnergy=15
startParasiteNumber=4
