#Konfiguracja symulacji: Wymieranie
#Wed Jan 21 16:31:39 CET 2026
energyLossForParasiteWithoutHost=0
energyLossPerDay=2
energyPerGrass=7
genomeLength=8
hostEnergyLossPerParasite=0
mapHeight=15
mapWidth=15
maximumMutations=2
minimumMutations=0
newGrassPerDay=2
saturationEnergy=15
startAnimalEnergy=10
startAnimalNumber=20
startGrassNumber=10
startParasiteEnergy=0
startParasiteNumber=0
